sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_TRAVISCI=phpcs

script: ./bin/run-wp-unit-tests.sh

after_script: ./bin/after-run-wp-unit-tests.sh
